#!/usr/bin/env bash
# This script loops from 1 to 10 then displays "bad luck" on the 4th loop, "good luck" on the 8th loop and "Best School" on other loops.

i=1
while ((i < 11))
do
	if [ $i == 4 ]
	then
		echo "bad luck"
	elif [ $i == 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
