#!/usr/bin/env bash
# This scripts displays The content of the current directory in a list format where only the part of the name after the first dash is displayed

for i in *
do
	result=$(echo "$i" | cut -d '-' -f 2)
	echo "$result"
done
